language: node_js
node_js:
  - 14

install:
  - npm install
  - sh setup.sh
  - git clone https://github.com/emscripten-core/emsdk.git
  - cd emsdk
  - ./emsdk install latest
  - ./emsdk activate latest
  - cd ..
  - source ./emsdk/emsdk_env.sh
  - npm run build

script:
- |
  npm run test
  npm run test-browser
  npm run semantic-release
